### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by SlimeyIceCream** [TetrisLitHub/T-Hack#2]
Upon attempting to launch the game with the mod in my mods folder I get error code zero, you might want to look into this.

**Comment by TetrisLitHub** [comment]
I seem to be getting this issue myself as well too when I run it outside of IntelliJ IDEA, I don't know what causes it but I'll try to fix it in the future. So far it seems like an issue with the build.gradle file but idk

**Comment by SlimeyIceCream** [comment]
I hope your able to fix it

**Comment by TetrisLitHub** [comment]
i might have found the issue, I believe it has to do with a Mixin problem but im not sure. will update soon.

**Comment by TetrisLitHub** [comment]
Issue has been fixed, though I had to remove Discord Rich Presence to get it to work properly :( I will update the release in a few minutes
